<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign up</title>
</head>
<body>
<main>
    <form action="/signUp" method="post">
        <input type="email" name="email" placeholder="example@email.com">
        <input type="phone" name="phone" placeholder="+7***-***-**-**">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="SIGN UP">
    </form>
</main>
</body>
</html>